server:
  port: 8889

spring:
  application:
    name: turbine

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  appConfig: microservice