spring:
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: dockerhost


#Dont have defaults... fail if config server not avaliable
#version:
#  name: Default
#  major: 0.1
#  build: 10