spring:
  application:
    name: microservice
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


version: Default Version