spring:
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: dockerhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Dont have defaults... fail if config server not avaliable
#version:
#  name: Default
#  major: 0.1
#  build: 10