
version: '2'

services:
    cassandra:
        image: cassandra:2.2.5
        ports:
            - 9042:9042
    kong:
        depends_on:
          - cassandra
        image: mashape/kong
        ports:
          - 8000:8000
          - 8443:8443
          - 8001:8001
          - 7946:7946
          - 7946:7946/udp
        links:
          - cassandra
        security_opt:
          - "seccomp:unconfined"
        restart: unless-stopped

    kong_dashboard:
      image: pgbi/kong-dashboard
      ports:
        - 9999:8080